// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('sample', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('sample', async function() {
    await driver.get("http://localhost:8080/")
    await driver.manage().window().setRect({ width: 1920, height: 1031 })
    {
      const element = await driver.findElement(By.css(".vue-slider-dot-handle-focus"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".vue-slider"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".vue-slider"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".vue-slider-dot-handle-focus")).click()
    {
      const element = await driver.findElement(By.css(".vue-slider-dot-handle-focus"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".vue-slider-dot-handle-focus"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".vue-slider-dot-handle-focus"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".vue-slider-dot-handle-focus")).click()
  })
})
